
spring.application.name=gestion_reparacion_colision
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

# Muestra en consola el SQL que ejecuta Hibernate (util al crear las tablas).
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
