pring.application.name=gestion_reparacion_colision
spring.datasource.url=jdbc:mysql://localhost:3306/gestion_reparacion_colision?createDatabaseIfNotExist=true&serverTimezone=America/Bogota
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

# Muestra en consola el SQL que ejecuta Hibernate (util al crear las tablas).
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
